### ISSUE TITLE
math.Rand doesn't support concurrency

### ISSUE THREAD

**Issue by TimSatke** [thoas/bokchoy#12]
I am using the Publish method like this
```
task, err := c.engine.Queue(queueName).Publish(context.Background(), entry)
if err != nil {
	c.errs <- err
	return
}
```
but eventually, I always encounter this error
```
panic: runtime error: index out of range [-2]

goroutine 9634 [running]:
math/rand.(*rngSource).Uint64(...)
        /usr/local/go/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(0xc0000af500, 0x290b9eb2ba0ec300)
        /usr/local/go/src/math/rand/rng.go:234 +0x93
math/rand.(*Rand).Int63(...)
        /usr/local/go/src/math/rand/rand.go:85
math/rand.read(0xc0030a3116, 0xa, 0xa, 0xc0058956b0, 0xc000098d70, 0xc000098d78, 0x10, 0xc0030a3110, 0xc000161400)
        /usr/local/go/src/math/rand/rand.go:272 +0x64
math/rand.(*Rand).Read(0xc000098d50, 0xc0030a3116, 0xa, 0xa, 0xc005895720, 0x100e258, 0x10)
        /usr/local/go/src/math/rand/rand.go:264 +0x106
io.ReadAtLeast(0x143b6a0, 0xc000098d50, 0xc0030a3116, 0xa, 0xa, 0xa, 0x16b8620, 0x4b8f430, 0xed5645a4e)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
github.com/oklog/ulid.New(0x16e7dd3e8ff, 0x143b6a0, 0xc000098d50, 0xc002ce5a40, 0xc00564c440, 0xc0030a30f0, 0xc0030a30e0)
        /Users/tsatke/go/pkg/mod/github.com/oklog/ulid@v1.3.1/ulid.go:96 +0xc9
github.com/oklog/ulid.MustNew(...)
        /Users/tsatke/go/pkg/mod/github.com/oklog/ulid@v1.3.1/ulid.go:105
github.com/thoas/bokchoy.id(0xc002ce5a40, 0x1000000010d75c7)
        /Users/tsatke/go/pkg/mod/github.com/thoas/bokchoy@v0.1.0/utils.go:16 +0x53
github.com/thoas/bokchoy.NewTask(0x13c59ad, 0xd, 0x13596a0, 0xc0030d86c0, 0x0, 0x0, 0x0, 0x10)
        /Users/tsatke/go/pkg/mod/github.com/thoas/bokchoy@v0.1.0/task.go:51 +0x6d
github.com/thoas/bokchoy.(*Queue).NewTask(0xc00012e000, 0x13596a0, 0xc0030d86c0, 0x0, 0x0, 0x0, 0x1)
        /Users/tsatke/go/pkg/mod/github.com/thoas/bokchoy@v0.1.0/queue.go:427 +0xd3
github.com/thoas/bokchoy.(*Queue).Publish(0xc00012e000, 0x14411c0, 0xc00001a078, 0x13596a0, 0xc0030d86c0, 0x0, 0x0, 0x0, 0xc004c83f40, 0x0, ...)
        /Users/tsatke/go/pkg/mod/github.com/thoas/bokchoy@v0.1.0/queue.go:445 +0x67
github.com/TimSatke/crawler/crawler.(*Crawler).Enqueue(0xc000098f30, 0xc002cecd80, 0x29)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:123 +0xd2
github.com/TimSatke/crawler/crawler.(*Crawler).processReference(0xc000098f30, 0xc0030ca680)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:235 +0x49
github.com/TimSatke/crawler/crawler.(*Crawler).processAnchorNode(0xc000098f30, 0xc003012c80, 0xc002072e70)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:230 +0x13b
github.com/TimSatke/crawler/crawler.(*Crawler).processHTMLInternal(0xc000098f30, 0xc003012c80, 0xc002072e70)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:199 +0x9e
github.com/TimSatke/crawler/crawler.(*Crawler).processHTMLInternal(0xc000098f30, 0xc003012c80, 0xc002072e00)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:202 +0x69
github.com/TimSatke/crawler/crawler.(*Crawler).processHTMLInternal(0xc000098f30, 0xc003012c80, 0xc002059030)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:202 +0x69
github.com/TimSatke/crawler/crawler.(*Crawler).processHTMLInternal(0xc000098f30, 0xc003012c80, 0xc001c16700)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:202 +0x69
github.com/TimSatke/crawler/crawler.(*Crawler).processHTMLInternal(0xc000098f30, 0xc003012c80, 0xc001c16690)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:202 +0x69
github.com/TimSatke/crawler/crawler.(*Crawler).processHTMLInternal(0xc000098f30, 0xc003012c80, 0xc001c16000)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:202 +0x69
github.com/TimSatke/crawler/crawler.(*Crawler).processHTMLInternal(0xc000098f30, 0xc003012c80, 0xc001c15a40)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:202 +0x69
github.com/TimSatke/crawler/crawler.(*Crawler).processHTMLInternal(0xc000098f30, 0xc003012c80, 0xc001c157a0)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:202 +0x69
github.com/TimSatke/crawler/crawler.(*Crawler).processHTMLInternal(0xc000098f30, 0xc003012c80, 0xc0065abea0)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:202 +0x69
github.com/TimSatke/crawler/crawler.(*Crawler).processHTMLInternal(0xc000098f30, 0xc003012c80, 0xc0065abdc0)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:202 +0x69
github.com/TimSatke/crawler/crawler.(*Crawler).processHTML(0xc000098f30, 0xc003012c80, 0x1b5fdd8, 0xc003e7ae70, 0xc003e7ae70, 0x0)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:193 +0x8f
github.com/TimSatke/crawler/crawler.(*Crawler).process(0xc000098f30, 0xc007073080, 0x22, 0x0, 0x0)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:184 +0x29d
github.com/TimSatke/crawler/crawler.(*Crawler).Worker(0xc000098f30, 0xc0005ebc80, 0x20, 0x20)
        /Users/tsatke/Desktop/crawler/crawler/crawler.go:149 +0xb8
github.com/thoas/bokchoy.HandlerFunc.Handle(0xc000124040, 0xc0005ebc80, 0x100d9e6, 0xc0001f7e68)
        /Users/tsatke/go/pkg/mod/github.com/thoas/bokchoy@v0.1.0/handler.go:8 +0x30
github.com/thoas/bokchoy.(*consumer).handleTask.func1.2(0xc0005ebc80, 0xc0001dc001, 0xc005227340)
        /Users/tsatke/go/pkg/mod/github.com/thoas/bokchoy@v0.1.0/consumer.go:73 +0x64
github.com/thoas/bokchoy.HandlerFunc.Handle(0xc005227320, 0xc0005ebc80, 0xc0001f7ec0, 0x12df49e)
        /Users/tsatke/go/pkg/mod/github.com/thoas/bokchoy@v0.1.0/handler.go:8 +0x30
github.com/thoas/bokchoy.(*consumer).handleRequest.func1(0xc0005ebc80, 0xc005227340, 0xc005227320)
        /Users/tsatke/go/pkg/mod/github.com/thoas/bokchoy@v0.1.0/consumer.go:162 +0x5c
github.com/thoas/bokchoy.HandlerFunc.Handle(0xc005227340, 0xc0005ebc80, 0x1, 0x143bf60)
        /Users/tsatke/go/pkg/mod/github.com/thoas/bokchoy@v0.1.0/handler.go:8 +0x30
github.com/thoas/bokchoy.(*consumer).handleTask.func1(0xc000b71c80, 0xc002484900, 0xc000130120, 0xc0005ebc80)
        /Users/tsatke/go/pkg/mod/github.com/thoas/bokchoy@v0.1.0/consumer.go:74 +0x1b8
created by github.com/thoas/bokchoy.(*consumer).handleTask
        /Users/tsatke/go/pkg/mod/github.com/thoas/bokchoy@v0.1.0/consumer.go:56 +0x13c
```

Why is that?

**Comment by thoas** [comment]
wow, impressive error it seems it comes from `oklog/ulid`. It doesn't seem related to bokchoy itself 🤔 

What's your system?

**Comment by TimSatke** [comment]
MacOS with Go1.13.
It is, because the error occurs because you use `ulid.MustNew`, and you should handle that error.

Don't have the project anymore, since it was just a scribble, but I was the lib at around 8000pub/s with a local redis instance and a concurrency level of 25. Everything else was default and/or from your readme.

**Comment by thoas** [comment]
Ok, thank you @TimSatke.

It seems related to `math.Rand`:

```
Please note that rand.Rand from the math package is not safe for concurrent use. Instantiate one per long living go-routine or use a sync.Pool if you want to avoid the potential contention of a locked rand.Source as its been frequently observed in the package level functions.
```

**Comment by thoas** [comment]
fixed in upstream

**Comment by TimSatke** [comment]
By 071d83d?
